# netlify.toml

[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.148.2"
  HUGO_EXTENDED = "true"
  HUGO_ENABLEGITINFO = "true"
  HUGO_ENVIRONMENT = "production"   # Hugo reads this; HUGO_ENV is legacy

[context.production.environment]
  HUGO_ENVIRONMENT = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

# Helpful content-types (keep your existing ones)
[[headers]]
  for = "*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"

[[headers]]
  for = "index.xml"
  [headers.values]
    Content-Type = "application/rss+xml"

# Keep your legacy blog redirect (leave as-is if it already works)
[[redirects]]
  from = "/20*"
  to = "https://ianmilli.wordpress.com/20:splat"
  status = 301
  force = true
